package spring.tutorial.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-13T20:12:57.124-04:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://service.tutorial.spring/", name = "IBanAcountService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBanAcountService {

    @WebMethod
    @RequestWrapper(localName = "addUserDetails", targetNamespace = "http://service.tutorial.spring/", className = "spring.tutorial.service.AddUserDetails")
    @ResponseWrapper(localName = "addUserDetailsResponse", targetNamespace = "http://service.tutorial.spring/", className = "spring.tutorial.service.AddUserDetailsResponse")
    public void addUserDetails(
        @WebParam(name = "userDetails", targetNamespace = "")
        spring.tutorial.service.UserDetails userDetails
    );

    @WebMethod
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://service.tutorial.spring/", className = "spring.tutorial.service.GetUserDetails")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://service.tutorial.spring/", className = "spring.tutorial.service.GetUserDetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public spring.tutorial.service.UserDetails getUserDetails(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    );
}
